service: authorization-service

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
    hello:
      handler: handler.hello
      events:
        - http:
            path: hello
            method: get 
            cors: true
            authorizer:
              name: basicAuthorizer
              resultTtlInSeconds: 0
              identitySource: method.request.header.Authorization
              type: token
    basicAuthorizer:
      handler: handler.basicAuthorizer




